vanlangcanteen/Models/CATEGORY.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vanlangcanteen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORY
    {
        public CATEGORY()
        {
            this.FOODs = new HashSet<FOOD>();
        }
    
        public int ID { get; set; }
        public string CATEGORY_CODE { get; set; }
        public string CATEGORY_NAME { get; set; }
        public string IMAGE_URL { get; set; }
        public bool STATUS { get; set; }
        public string EMAIL { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<int> AGE { get; set; }
        public Nullable<decimal> PRICE { get; set; }
    
        public virtual ICollection<FOOD> FOODs { get; set; }
    }
}

vanlangcanteen/Areas/Admin/Controllers/CATEGORiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using vanlangcanteen.Models;
using vanlangcanteen.Areas.Admin.Middleware;
using System.Transactions;

namespace vanlangcanteen.Areas.Admin.Controllers
{
    [LoginVerification]
    public class CATEGORiesController : Controller
    {
        private QUANLYCANTEENEntities db = new QUANLYCANTEENEntities();
        private const string PICTURE_PATH = "~/Upload/Categories/";
        // GET: Admin/CATEGORies
        public ActionResult Index()
        {
            var product = db.CATEGORies.ToList().OrderByDescending(x => x.ID).ToList();
            return View(product);
        }

        // GET: Admin/CATEGORies/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CATEGORY cATEGORY = db.CATEGORies.Find(id);
            if (cATEGORY == null)
            {
                return HttpNotFound();
            }
            return View(cATEGORY);
        }

        public ActionResult Picture(int id)
        {
            var path = Server.MapPath(PICTURE_PATH);
            return File(path + id, "images");
        }
        [HttpGet]
        // GET: Admin/CATEGORies/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/CATEGORies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,CATEGORY_CODE,CATEGORY_NAME,IMAGE_URL,STATUS")] CATEGORY cATEGORY, HttpPostedFileBase picture)
        {
            var product = new CATEGORY();
            if (picture != null)
            {
                using (var scope = new TransactionScope())
                {
                    product.CATEGORY_CODE = cATEGORY.CATEGORY_CODE;
                    product.CATEGORY_NAME = cATEGORY.CATEGORY_NAME;
                    product.STATUS = cATEGORY.STATUS;
                    db.CATEGORies.Add(product);
                    db.SaveChanges();

                    var path = Server.MapPath(PICTURE_PATH);
                    picture.SaveAs(path + product.ID);
                    scope.Complete();
                }
            }
            else
            {
                ModelState.AddModelError("", "Picture not found!");
            }
            return RedirectToAction("Index");
        }

        // GET: Admin/CATEGORies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CATEGORY cATEGORY = db.CATEGORies.Find(id);
            if (cATEGORY == null)
            {
                return HttpNotFound();
            }
            return View(cATEGORY);
        }

        // POST: Admin/CATEGORies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, CATEGORY cATEGORY, HttpPostedFileBase picture)
        {
            var product = db.CATEGORies.Find(id);
            if (ModelState.IsValid)
            {
                using (var scope = new TransactionScope())
                {
                    product.ID = cATEGORY.ID;
                    product.CATEGORY_CODE = cATEGORY.CATEGORY_CODE;
                    product.CATEGORY_NAME = cATEGORY.CATEGORY_NAME;
                    product.STATUS = cATEGORY.STATUS;

                    db.Entry(product).State = EntityState.Modified;
                    db.SaveChanges();

                    if (picture != null)
                    {
                        //System.IO.File.WriteAllText(@"D:\test.txt", "ok");
                        var path = Server.MapPath(PICTURE_PATH);
                        picture.SaveAs(path + cATEGORY.ID);
                    }

                    scope.Complete();
                    return RedirectToAction("Index");

                }
            }
            return View(cATEGORY);
        }

        // GET: Admin/CATEGORies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CATEGORY cATEGORY = db.CATEGORies.Find(id);
            if (cATEGORY == null)
            {
                return HttpNotFound();
            }
            return View(cATEGORY);
        }

        // POST: Admin/CATEGORies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CATEGORY cATEGORY = db.CATEGORies.Find(id);
            db.CATEGORies.Remove(cATEGORY);

            var path = Server.MapPath(PICTURE_PATH);
            System.IO.File.Delete(path + id);

            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

vanlangcanteen/Areas/Admin/Views/CATEGORies/Create.cshtml
@model vanlangcanteen.Models.CATEGORY

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "CATEGORies", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>CATEGORY</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.CATEGORY_CODE, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CATEGORY_CODE, new { htmlAttributes = new { @class = "form-control", @requied = true  } })
            @Html.ValidationMessageFor(model => model.CATEGORY_CODE, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CATEGORY_NAME, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CATEGORY_NAME, new { htmlAttributes = new { @class = "form-control", @requied = true } })
            @Html.ValidationMessageFor(model => model.CATEGORY_NAME, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.IMAGE_URL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IMAGE_URL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IMAGE_URL, "", new { @class = "text-danger" })
            </div>
        </div>*@
    @Html.LabelFor(model => model.IMAGE_URL, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        <div class="form-group">
            <input class="form-control" type="file" name="Picture" id="IMG" onchange="readPicture(this)" accept="image/jpeg,image/gif,image/png" />
            <img id="Picture" width="300" />
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.STATUS, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.STATUS)
                @Html.ValidationMessageFor(model => model.STATUS, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        function readPicture(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('img#Picture').attr('src', e.target.result).width(200).height(250);
                };
                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>
}

vanlangcanteen/Areas/Admin/Views/CATEGORies/Delete.cshtml
@model vanlangcanteen.Models.CATEGORY

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CATEGORY</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CATEGORY_CODE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CATEGORY_CODE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CATEGORY_NAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CATEGORY_NAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IMAGE_URL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IMAGE_URL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.STATUS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.STATUS)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

vanlangcanteen/Areas/Admin/Views/CATEGORies/Details.cshtml
@model vanlangcanteen.Models.CATEGORY

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>CATEGORY</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CATEGORY_CODE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CATEGORY_CODE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CATEGORY_NAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CATEGORY_NAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IMAGE_URL)
        </dt>

        <dd>
            <img id="Picture" src="@Url.Action("Picture", new { Model.ID})" width="300"/>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.STATUS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.STATUS)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

vanlangcanteen/Areas/Admin/Views/CATEGORies/Edit.cshtml
@model vanlangcanteen.Models.CATEGORY

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit</h2>


<form method="post" enctype="multipart/form-data">
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>CATEGORY</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.CATEGORY_CODE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CATEGORY_CODE, new { htmlAttributes = new { @class = "form-control", @requied = true } })
                @Html.ValidationMessageFor(model => model.CATEGORY_CODE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CATEGORY_NAME, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CATEGORY_NAME, new { htmlAttributes = new { @class = "form-control", @requied = true } })
                @Html.ValidationMessageFor(model => model.CATEGORY_NAME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IMAGE_URL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input class="form-control" type="file" name="picture" id="IMG" onchange="readPicture(this)" accept="image/jpeg,image/gif,image/png" />
                <img id="picture" src="@Url.Action("Picture", new { Model.ID})" width="250" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.STATUS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.STATUS)
                    @Html.ValidationMessageFor(model => model.STATUS, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts {

    <script>
        function readPicture(input) {
            if (input.files && input.files[0])
                var reader = new FileReader();
            reader.onload = function (e) {
                $('img#picture').attr('src', e.target.result)
            };
            reader.readAsDataURL(input.files[0])
        }
    </script>

    @Scripts.Render("~/bundles/jqueryval")
}

vanlangcanteen/Areas/Admin/Views/CATEGORies/Index.cshtml
@model IEnumerable<vanlangcanteen.Models.CATEGORY>

@{
    ViewBag.Title = "Loại đồ ăn";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Quản Lý Loại Thực Phẩm</h2>
<p>
    <a class="text-capitalize" href="@Url.Action("Create")">
        <i class="fas fa-plus-circle"> Thêm danh mục món ăn</i>
    </a>
</p>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>SB Admin - Start Bootstrap Template</title>
    <!-- Bootstrap core CSS-->
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom fonts for this template-->
    <link href="~/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <!-- Page level plugin CSS-->
    <link href="~/vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="~/Content/sb-admin.css" rel="stylesheet" />
</head>

<body class="fixed-nav sticky-footer bg-dark" id="page-top">
    <div class="container-fluid">
        <!-- Example DataTables Card-->
        <div class="card mb-3">
            <div class="card-header">
                <i class="fa fa-table"></i> Danh mục thực phẩm
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>
                                    Mã loại đồ ăn
                                </th>
                                <th>
                                    Tên loại đồ ăn
                                </th>
                                <th>
                                    Hình ảnh
                                </th>
                                <th>
                                    Trạng thái
                                </th>
                                <th></th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.CATEGORY_CODE)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.CATEGORY_NAME)
                                    </td>
                                    <td>
                                        <img src="@Url.Action("Picture", new { item.ID})" width="100" />
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.STATUS)
                                    </td>
                                    <td>
                                        <a href="@Url.Action("Edit", new { id = item.ID })"><i class="fas fa-edit"></i></a>|
                                        <a href="@Url.Action("Details", new { id = item.ID })"><i class="fas fa-eye"></i></a> |
                                        <a href="@Url.Action("Delete", new { id = item.ID })"><i class="fas fa-trash"></i></a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
        </div>


        <!-- Scroll to Top Button-->
        <a class="scroll-to-top rounded" href="#page-top">
            <i class="fa fa-angle-up"></i>
        </a>

        <!-- Bootstrap core JavaScript-->
        <script src="~/vendor/jquery/jquery.min.js"></script>
        <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
        <!-- Core plugin JavaScript-->
        <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>
        <!-- Page level plugin JavaScript-->
        <script src="~/vendor/datatables/dataTables.bootstrap4.js"></script>
        <script src="~/vendor/datatables/jquery.dataTables.js"></script>
        <!-- Custom scripts for all pages-->
        <script src="~/Scripts/sb-admin.min.js"></script>
        <!-- Custom scripts for this page-->
        <script src="~/Scripts/sb-admin-datatables.min.js"></script>
    </div>
</body>

</html>