vanlangcanteen/Models/FOOD.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vanlangcanteen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOOD
    {
        public FOOD()
        {
            this.MENUs = new HashSet<MENU>();
        }
    
        public int ID { get; set; }
        public string FOOD_CODE { get; set; }
        public string FOOD_NAME { get; set; }
        public int CATEGORY_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public int PRICE { get; set; }
        public string IMAGE_URL { get; set; }
        public bool STATUS { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual ICollection<MENU> MENUs { get; set; }
    }
}

vanlangcanteen/Areas/Admin/Controllers/FOODsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Transactions;
using vanlangcanteen.Models;
using vanlangcanteen.Areas.Admin.Middleware;

namespace vanlangcanteen.Areas.Admin.Controllers
{
    [LoginVerification]
    public class FOODsController : Controller
    {
        private QUANLYCANTEENEntities db = new QUANLYCANTEENEntities();
        private const string PICTURE_PATH = "~/Upload/Foods/";

        // GET: Admin/FOODs
        public ActionResult Index()
        {
            var fOODs = db.FOODs.ToList().OrderByDescending(x => x.ID).ToList();
            return View(fOODs);
        }

        // GET: Admin/FOODs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FOOD fOOD = db.FOODs.Find(id);
            if (fOOD == null)
            {
                return HttpNotFound();
            }
            return View(fOOD);
        }
        public ActionResult Picture(int id)
        {
            var path = Server.MapPath(PICTURE_PATH);
            return File(path + id, "images");
        }
        // GET: Admin/FOODs/Create
        public ActionResult Create()
        {
            ViewBag.CATEGORY_ID = new SelectList(db.CATEGORies, "ID", "CATEGORY_CODE");
            return View();
        }

        // POST: Admin/FOODs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,FOOD_CODE,FOOD_NAME,CATEGORY_ID,DESCRIPTION,PRICE,IMAGE_URL,STATUS")] FOOD fOOD, HttpPostedFileBase picture)
        {
            if (ModelState.IsValid)
            {
                var product = new FOOD();
                if (picture != null)
                {
                    using (var scope = new TransactionScope())
                    {
                        product.ID = fOOD.ID;
                        product.FOOD_CODE = fOOD.FOOD_CODE;
                        product.FOOD_NAME = fOOD.FOOD_NAME;
                        product.CATEGORY_ID = fOOD.CATEGORY_ID;
                        product.DESCRIPTION = fOOD.DESCRIPTION;
                        product.PRICE = fOOD.PRICE;
                        product.STATUS = fOOD.STATUS;
                        db.FOODs.Add(product);
                        db.SaveChanges();

                        var path = Server.MapPath(PICTURE_PATH);
                        picture.SaveAs(path + product.ID);

                        scope.Complete();
                    }
                }
                else ModelState.AddModelError("", "Hình ảnh không được tìm thấy");
            }
            ViewBag.CATEGORY_ID = new SelectList(db.CATEGORies, "ID", "CATEGORY_CODE", fOOD.CATEGORY_ID);
            return RedirectToAction("Index");
        }

        // GET: Admin/FOODs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FOOD fOOD = db.FOODs.Find(id);
            if (fOOD == null)
            {
                return HttpNotFound();
            }
            ViewBag.CATEGORY_ID = new SelectList(db.CATEGORies, "ID", "CATEGORY_CODE", fOOD.CATEGORY_ID);
            return View(fOOD);
        }

        // POST: Admin/FOODs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id,[Bind(Include = "ID,FOOD_CODE,FOOD_NAME,CATEGORY_ID,DESCRIPTION,PRICE,IMAGE_URL,STATUS")] FOOD fOOD, HttpPostedFileBase picture)
        {
            if (ModelState.IsValid)
            {
                var product = db.FOODs.Find(id);
                if (ModelState.IsValid)
                {
                    using (var scope = new TransactionScope())
                    {
                        product.ID = fOOD.ID;
                        product.FOOD_CODE = fOOD.FOOD_CODE;
                        product.FOOD_NAME = fOOD.FOOD_NAME;
                        product.CATEGORY_ID = fOOD.CATEGORY_ID;
                        product.DESCRIPTION = fOOD.DESCRIPTION;
                        product.PRICE = fOOD.PRICE;
                        product.STATUS = fOOD.STATUS;

                        db.Entry(product).State = EntityState.Modified;
                        db.SaveChanges();

                        if (picture != null)
                        {
                            var path = Server.MapPath(PICTURE_PATH);
                            picture.SaveAs(path + product.ID);
                        }

                        scope.Complete();
                        return RedirectToAction("Index");

                    }
                }
                db.Entry(fOOD).State = EntityState.Modified;
            }
            ViewBag.CATEGORY_ID = new SelectList(db.CATEGORies, "ID", "CATEGORY_CODE", fOOD.CATEGORY_ID);
            return View(fOOD);
        }

        // GET: Admin/FOODs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FOOD fOOD = db.FOODs.Find(id);
            if (fOOD == null)
            {
                return HttpNotFound();
            }
            return View(fOOD);
        }

        // POST: Admin/FOODs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            FOOD fOOD = db.FOODs.Find(id);
            db.FOODs.Remove(fOOD);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

vanlangcanteen/Areas/Admin/Views/FOODs/Create.cshtml
@model vanlangcanteen.Models.FOOD

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "FOODs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>FOOD</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger"})
        <div class="form-group">
            @Html.LabelFor(model => model.FOOD_CODE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FOOD_CODE, new { htmlAttributes = new { @class = "form-control", @readonly = true} })
                @Html.ValidationMessageFor(model => model.FOOD_CODE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FOOD_NAME, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FOOD_NAME, new { htmlAttributes = new { @class = "form-control", @requied = true, @minLength = "1", @maxLength = "1000" } })
                @Html.ValidationMessageFor(model => model.FOOD_NAME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CATEGORY_ID, "CATEGORY_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CATEGORY_ID", null, htmlAttributes: new { @class = "form-control", @requied = true })
                @Html.ValidationMessageFor(model => model.CATEGORY_ID, "", new { @class = "text-danger" })
            </div>
        </div>  

        <div class="form-group">
            @Html.LabelFor(model => model.DESCRIPTION, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DESCRIPTION, new { htmlAttributes = new { @class = "form-control", @requied = true, @minLength = "1", @maxLength = "1000" } })
                @Html.ValidationMessageFor(model => model.DESCRIPTION, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PRICE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PRICE, new { htmlAttributes = new { @class = "form-control", @requied = true, @min = "1000", @max = "1000000" } })
                @Html.ValidationMessageFor(model => model.PRICE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IMAGE_URL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input class="form-control" type="file" name="Picture" id="IMG" onchange="readPicture(this)" accept="image/jpeg,image/gif,image/png" />
                <img id="Picture" width="300" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.STATUS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.STATUS)
                    @Html.ValidationMessageFor(model => model.STATUS, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        function readPicture(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('img#Picture').attr('src', e.target.result).width(200).height(250);
                };
                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>
}

vanlangcanteen/Areas/Admin/Views/FOODs/Delete.cshtml
@model vanlangcanteen.Models.FOOD

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>FOOD</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FOOD_CODE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FOOD_CODE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FOOD_NAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FOOD_NAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DESCRIPTION)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DESCRIPTION)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PRICE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PRICE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IMAGE_URL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IMAGE_URL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.STATUS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.STATUS)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CATEGORY.CATEGORY_CODE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CATEGORY.CATEGORY_CODE)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

vanlangcanteen/Areas/Admin/Views/FOODs/Details.cshtml
@model vanlangcanteen.Models.FOOD

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>FOOD</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FOOD_CODE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FOOD_CODE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FOOD_NAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FOOD_NAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DESCRIPTION)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DESCRIPTION)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PRICE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PRICE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IMAGE_URL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IMAGE_URL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.STATUS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.STATUS)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CATEGORY.CATEGORY_CODE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CATEGORY.CATEGORY_CODE)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

vanlangcanteen/Areas/Admin/Views/FOODs/Edit.cshtml
@model vanlangcanteen.Models.FOOD

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit</h2>


<form method="post" enctype="multipart/form-data">
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>FOOD</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.FOOD_CODE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FOOD_CODE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FOOD_CODE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FOOD_NAME, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FOOD_NAME, new { htmlAttributes = new { @class = "form-control", @requied = true, @minLength = "1", @maxLength = "1000" } })
                @Html.ValidationMessageFor(model => model.FOOD_NAME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CATEGORY_ID, "CATEGORY_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CATEGORY_ID", null, htmlAttributes: new { @class = "form-control", @requied = true })
                @Html.ValidationMessageFor(model => model.CATEGORY_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DESCRIPTION, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DESCRIPTION, new { htmlAttributes = new { @class = "form-control", @requied = true, @minLength = "1", @maxLength = "1000" } })
                @Html.ValidationMessageFor(model => model.DESCRIPTION, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PRICE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PRICE, new { htmlAttributes = new { @class = "form-control", @requied = true, @min = "1000", @max = "1000000" } })
                @Html.ValidationMessageFor(model => model.PRICE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IMAGE_URL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input class="form-control" type="file" name="Picture" id="IMG" onchange="readPicture(this)" accept="image/jpeg,image/gif,image/png" />
                <img id="Picture" src="@Url.Action("Picture", new { Model.ID})" width="250" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.STATUS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.STATUS)
                    @Html.ValidationMessageFor(model => model.STATUS, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
 </form>

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
    @section Scripts {

        <script>
            function readPicture(input) {
                if (input.files && input.files[0])
                    var reader = new FileReader();
                reader.onload = function (e) {
                    $('img#Picture').attr('src', e.target.result)
                };
                reader.readAsDataURL(input.files[0])
            }
        </script>

        @Scripts.Render("~/bundles/jqueryval")
    }

vanlangcanteen/Areas/Admin/Views/FOODs/Index.cshtml
@model IEnumerable<vanlangcanteen.Models.FOOD>

@{
    ViewBag.Title = "Món ăn";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Quản Lý Món Ăn</h2>

<p>
    <a class="text-capitalize" href="@Url.Action("Create")">
        <i class="fas fa-plus-circle"> Thêm món ăn</i>
    </a>
</p>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>SB Admin - Start Bootstrap Template</title>
    <!-- Bootstrap core CSS-->
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom fonts for this template-->
    <link href="~/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <!-- Page level plugin CSS-->
    <link href="~/vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="~/Content/sb-admin.css" rel="stylesheet" />
</head>

<body class="fixed-nav sticky-footer bg-dark" id="page-top">
    <div class="container-fluid">
        <!-- Example DataTables Card-->
        <div class="card mb-3">
            <div class="card-header">
                <i class="fa fa-table"></i> Danh mục món ăn
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>FOOD_CODE</th>
                                <th>FOOD_NAME</th>
                                <th>DESCRIPTIONDESCRIPTION</th>
                                <th>PRICE</th>
                                <th>IMAGE_URL</th>
                                <th>STATUS</th>
                                <th>CATEGORY_CODE</th>
                            </tr>
                        </thead>

                        <tbody>
                            <tr>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>

                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.FOOD_CODE)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.FOOD_NAME)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.DESCRIPTION)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.PRICE)
                                    </td>
                                    <td>
                                        <img src="@Url.Action("Picture", new { item.ID})" width="100" />
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.STATUS)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.CATEGORY.CATEGORY_CODE)
                                    </td>
                                    <td>
                                        <a href="@Url.Action("Edit", new { id = item.ID })"><i class="fas fa-edit"></i></a>|
                                        <a href="@Url.Action("Details", new { id = item.ID })"><i class="fas fa-eye"></i></a> |
                                        <a href="@Url.Action("Delete", new { id = item.ID })"><i class="fas fa-trash"></i></a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
        </div>


        <!-- Scroll to Top Button-->
        <a class="scroll-to-top rounded" href="#page-top">
            <i class="fa fa-angle-up"></i>
        </a>

        <!-- Bootstrap core JavaScript-->
        <script src="~/vendor/jquery/jquery.min.js"></script>
        <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
        <!-- Core plugin JavaScript-->
        <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>
        <!-- Page level plugin JavaScript-->
        <script src="~/vendor/datatables/jquery.dataTables.js"></script>
        <script src="~/vendor/datatables/dataTables.bootstrap4.js"></script>
        <!-- Custom scripts for all pages-->
        <script src="~/Scripts/sb-admin.min.js"></script>
        <!-- Custom scripts for this page-->
        <script src="~/Scripts/sb-admin-datatables.min.js"></script>
    </div>
</body>

</html>